vektor-inc/vk-dynamic-if-block

readme.txt
src/block.json
src/index.js
src/index.php
tests/test-dynamic-if.php
vk-dynamic-if-block.php

https://github.com/vektor-inc/vk-dynamic-if-block/issues/7

Add exclusion setting

---

src/index.php

条件が増えたときに処理しやすいように条件分岐処理を各条件で分岐してから統合するように変更

条件分岐処理のリファクタリング

---

readme.txt
src/index.js
src/transforms.js
vk-dynamic-if-block.php

https://github.com/vektor-inc/vk-dynamic-if-block/issues/25
いくつかのブロックでラップ・アンラップできることを確認しました。

ラップ・アンラップする機能を追加

---

readme.txt
src/block.json
src/editor.scss
src/index.js
src/index.php
tests/test-dynamic-if.php

https://github.com/vektor-inc/vk-dynamic-if-block/issues/27

【確認待ち】ユーザー権限による条件分岐を追加

---

readme.txt
src/index.js
vk-dynamic-if-block.php

https://github.com/vektor-inc/vk-dynamic-if-block/issues/35
ブロックにチェックされているユーザーロールが表示されることを確認しました。

【確認待ち】編集画面のブロックにUserRoleのラベルを追加

---

readme.txt
src/index.php
tests/test-dynamic-if.php
vk-dynamic-if-block.php

ユーザー権限での条件分岐が正常に動作していない
テストのためにユーザー権限を第三引数で受け取っていたが、実際には第三引数に他の内容が入ってくるため誤動作していたため、テスト用のユーザー権限は attributes に持たせるように変更

[ Change version ] 0.6.2 / Fix the bug in conditional branching based on user roles.

---

readme.txt
src/index.js
src/index.php
tests/test-dynamic-if.php
vk-dynamic-if-block.php

ACF でフィールドの返り値形式を H:i に指定しても実際に返ってくるのが H:i:s 形式なので、条件分岐がちゃんと動作しない
Y-m-d H:i:s 形式をサポート
* 
*
*
---
* プルしたか？
* ビルドしたか？

[ Change version ] 0.6.3 / Fixed a bug related to the period setting when referencing a custom field.

---

.gitignore
readme.txt
src/block.json
src/index.js
src/index.php
tests/test-dynamic-if.php
vk-dynamic-if-block.php

言語での条件分岐機能追加
*
*
*
---
* プルしたか？
* ビルドしたか？

[ Change version ] 0.8.0 / Add a conditional branching function based on language.

---

src/index.php

言語での条件選択に en_US が無いので追加。
言語選択に en_US を追加
`'https://api.wordpress.org/translations/core/1.0/'` への通信がエラーになってもとりあえず en_US / '未指定' は出すように。
* wp_get_available_translations とか使った方が良いのかもしれないけどとりあえず。
*
*
*
---
* プルしたか？
* ビルドしたか？

言語選択に en_US を追加

---

readme.txt
src/block.json
src/index.js

https://github.com/vektor-inc/vk-blocks-pro/issues/2289#issuecomment-2446050765
blocks.json や index.js の apiVersion を 3 に変更することで、ズームアウトのトグルがエディターツールバーに常に表示されるよう修正しました。
1. プラグインで「VK Dynamic If Block」 だけを有効にする。
2. 新規固定ページで「Dynamic If」のブロックを追加する。
3. エディターツールバーにズームアウトのトグルや「ドラッグしてサイズ変更」が常に表示されており、さらに機能していることを確認。
4. 保存し、フロントエンドでブロックが表示、機能していることを確認。
（　どこかのデモサイトかテストサーバーにデプロイ済みなどで確認できる場合はそのURL　）
実装者と同じ確認を行ってください。
その他気になる点があれば適宜ご確認ください。
---
* プルしたか？
* ビルドしたか？

エディターツールバーにズームアウトのトグルが常に表示されない不具合を修正

---

readme.txt
src/index.js

#61 
除外指定が有効な場合、条件ラベルに「!」を付けて表示するようにしました。
以下はworksかworks以外かで指定しており、除外指定をしてある方だけ「! is_single / works」になります。
「!」が出るか出ないかを切り分けてるだけなのでお一人で大丈夫です。
1. 固定ページにDynamic If ブロックを設定し右パネルの「除外指定」をON
2. 右上のラベルに「!」が表示されることを確認
3. 実際に除外になること、また、他の機能を阻害しないことを確認。
---
* プルしたか？
* ビルドしたか？

【確認中】[ 機能追加 ] 除外指定の時に編集画面に出る右上のラベルで「!」が出るようにしました

---

readme.txt

https://github.com/vektor-inc/vk-dynamic-if-block/issues/63
- readme.txt の Tested up to:  を 6.8 に変更しました
- WordPress 6.8 で VK Dynamic If Block が問題なく使用できること
- readme.txt の Tested up to:  が 6.8 になっているこ
上記を確認しました。
- WordPress 6.8 で VK Dynamic If Block が問題なく使用できること
- readme.txt の Tested up to:  が 6.8 になっているこ
上記を確認お願いします。
---
* プルしたか？
* ビルドしたか？

Tested up to: 6.8

---

.github/workflows/release.yml
.github/workflows/test.yml

wp-env の起動がうまくいかなくて失敗するのを防ぎたかった
- GitHub Action の Workflow を修正して wp-env の起動による失敗が減るように
- GitHub Action が通過していること
- コードレビュー
- GitHub Action が通過していること
---
* プルしたか？
* ビルドしたか？

GitHub Action の Workflow を修正

---

readme.txt
vk-dynamic-if-block.php

https://github.com/vektor-inc/vk-dynamic-if-block/issues/69#event-18536113828

[ 不具合修正 ] readme のタイポ修正

---

readme.txt
src/index.php

https://github.com/vektor-inc/vk-dynamic-if-block/issues/71
- 選択可能なユーザーの対象を投稿が1件以上公開済みの寄稿者以上に限定
1. WordPress で寄稿者、投稿者、編集者、管理者のユーザーアカウントを作成
2. 適当なユーザーで適当な投稿タイプで記事を公開
3. VK Dynamic If Block のユーザー選択画面で公開済みの投稿があるユーザーのみが選択できる
上記を確認しました。
ユーザーの絞りかたはこれで OK か
---
* プルしたか？
* ビルドしたか？

選択可能なユーザーの対象を投稿が1件以上公開済みの寄稿者以上に限定

---

readme.txt
src/index.js
src/index.php
tests/test-dynamic-if.php

本当は https://github.com/vektor-inc/vk-dynamic-if-block/pull/78 の内容だが、
https://github.com/vektor-inc/vk-dynamic-if-block/pull/78 の処理を失敗してぐちゃぐちゃになってしまったので、
0系のメインブランチを別途設定してやりなおし
https://github.com/vektor-inc/vk-dynamic-if-block/pull/78

[ Specification change ] Add the condition !is_year() && !is_month() && !is_date() for Post Type Archives.

---

admin-notice.php
readme.txt
vk-dynamic-if-block.php

https://github.com/vektor-inc/vk-dynamic-if-block/issues/80
*
*
*
---
* プルしたか？
* ビルドしたか？

[ 0系 ] アップデートのアラート追加

---

src/block.json
src/constants.js
src/index.js
src/transforms.js

#87 
ブロック複製時に条件が共有される問題を修正しました。
ブロックを複製する際に、条件のIDが正しく生成されず、複製されたブロックが同じ条件オブジェクトを参照していたため、一方のブロックの条件を変更すると、もう一方のブロックも同じ条件になってしまってました。
- `regenerateConditionIds`関数を追加し、ブロックの複製時に確実に新しいIDが生成されるようにしました
- 条件の更新時に深いコピーを使用することで、オブジェクトの参照が共有されることを防ぎました
- `transforms`ファイルを修正し、ブロックの変換時に新しいIDを生成するようにしました
- `useEffect`でIDの重複をチェックし、重複がある場合は新しいIDを生成するようにしました
1. ページタイプや投稿タイプなどで固定ページにして、親ページあり条件の if ブロックを配置
2. ブロックを複製
3. 複製したものを親ページありから子ページありに変更
4. 保存して再読み込みしても手順3の設定がそのまま引き継がれていることを確認
上記以外で様々な条件で複製しても問題がないかを確認いただけたらと思います。
---
* プルしたか？
* ビルドしたか？
* …

[ 不具合修正 ] ブロックを複製した際に条件IDが重複してすべてのブロックが同じ条件を共有してしまう問題を修正し、各複製されたブロックが一意の条件IDを取得するように修正

---

readme.txt
src/index.js

[ Other ] Fix translation

---

readme.txt
src/index.js

https://github.com/vektor-inc/vk-dynamic-if-block/issues/98
_x 使えるようになってなかったので修正（・ｗ・

[ 不具合修正 ] 言語選択にするとクラッシュする不具合修正

---

readme.txt
src/index.js

#102 
表示期間条件で「このブロックから直接指定」を選択した際に日付入力フィールドが表示されない問題を修正しました。
- `periodSpecificationMethod`の初期値が未設定の場合も日付入力フィールドを表示するように条件を修正
- 条件タイプが`period`に変更された際の初期値設定を追加（`periodSpecificationMethod: 'direct'`をデフォルトに設定）
→ この修正は既存のUIコンポーネントの表示条件を変更するのみで、ロジックの変更はないため、スキップ。
1. 固定ページ等にDynamic Ifブロックを追加
2. 「表示期間」> **制限なし以外**を選択で「このブロックから直接指定」が同時に表示された際、日付を選択できることを確認
3. 制限なし以外で日時設定をし、保存
4. フロントエンドで表示期間設定と設定日時通りの表示/非表示になることを確認
既存の機能に影響がないことを確認
制限なし以外の期間表示設定を全て確認してください。
---
* プルしたか？
* ビルドしたか？

[ 不具合修正 ] 表示期間条件を選択した際に初期の「このブロックから直接指定」に日付入力フィールドが表示されない問題を修正
